### ISSUE TITLE
Generating e-Pub fails on remote server

### ISSUE THREAD

**Issue by ghsnd** [freme-project/e-Publishing#19]
When sending the file [files.zip](http://users.ugent.be/~ghaesend/files.zip) to the e-Publishing service, the resulting epub file is not complete. In the epub, only a part of the file `OEPBS/content.opf` is written.

_on the FREME server_, it works on version 0.4 of the Broker, but not on the dev. version. 

When running _on a local machine_ there is no problem using the dev version; we cannot reproduce it.

The command is

```
curl --form "htmlZip=@files.zip" --form metadata='{"titles":["Semantic Book"],"creators":[{"firstName": "Joske","lastName": "Vermeulen","roles":["author"]}],"subjects":["news","world"],"language":"en","identifier":{"value":"urn:1235-568-78910"},"tableOfContents":[{"title":"Introduction","resource":"introduction.html"},{"title":"Etymology","resource":"etymology.html"},{"title":"History","resource":"history.html"}]}' http://api-dev.freme-project.eu/current/e-publishing/html > semantic_book.epub
```

The epub file is just a zip file, so it is easy to see what's in it.

So the first questions ( @jnehring ) are:
- is there anything changed on the FREME server that possibly limits the size of the response?
- is it possible for us to see logfiles on the dev server (can we get a limited account, or are the logs published somewhere)?
- what exact JVM is used?

**Comment by jnehring** [comment]
> is there anything changed on the FREME server that possibly limits the size of the response?

I have configured very large request size limits, I think 2 GB. But I never tested large requests. How large is your request?

> is it possible for us to see logfiles on the dev server (can we get a limited account, or are the logs published somewhere)?

I send you credentials

> what exact JVM is used?

$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Does this answer your question?

**Comment by ghsnd** [comment]
Yes, thanks.

The file is only about 2 MB, so that won't be the problem.

**Comment by jnehring** [comment]
In the broker.log you can find

```
ERROR   2015-12-09 15:51:54,582 [http-nio-8084-exec-1] nl.siegmann.epublib.epub.Epub3Writer  -
org.xml.sax.SAXParseException; lineNumber: 150; columnNumber: 23; The entity "nbsp" was referenced, but not declared.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at nl.siegmann.epublib.epub.Epub3PackageDocumentWriter.writeItem(Epub3PackageDocumentWriter.java:151)
        at nl.siegmann.epublib.epub.Epub3PackageDocumentWriter.writeManifest(Epub3PackageDocumentWriter.java:95)
        at nl.siegmann.epublib.epub.Epub3PackageDocumentWriter.write(Epub3PackageDocumentWriter.java:51)
        at nl.siegmann.epublib.epub.Epub3Writer.writePackageDocument(Epub3Writer.java:72)
        at nl.siegmann.epublib.epub.Epub3Writer.write(Epub3Writer.java:45)
        at eu.freme.eservices.epublishing.EPubCreatorImpl.onEnd(EPubCreatorImpl.java:262)
        at eu.freme.eservices.epublishing.EPublishingService.createEPUB(EPublishingService.java:67)
        at eu.freme.broker.eservices.EPublishing.htmlToEPub(EPublishing.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62
```

Unfortunately this is not new information to @pheyvaer

**Comment by pheyvaer** [comment]
@jnehring As discussed at the F2F, you were going to check this, right?

**Comment by jnehring** [comment]
Thanks for the reminder. I will take a look at the issue.

**Comment by jnehring** [comment]
I tried to reproduce the bug. I used your CURL request and your files.zip. I cannot see any error messages in the logfile on freme-dev. Also I can open the ebook with Readium. The file OEPBS/content.opf looks like a valid XML file to me. 

I renamed content.opf to content.txt and attached it to this issue. @pheyvaer can you please check if the file is ok?

[content.txt](https://github.com/freme-project/e-Publishing/files/78520/content.txt)

**Comment by pheyvaer** [comment]
It just happened again ...

**Comment by pheyvaer** [comment]
But now it also happens locally.

**Comment by jnehring** [comment]
I could not reproduce it on my windows 8 machine.

**Comment by pheyvaer** [comment]
It might be caused by a specific html file on our side. We are looking into it.

**Comment by pheyvaer** [comment]
UPDATE: so it works with the example at the beginning of this issue. However, with our current example (the Semantic Book) it doesn't.

```
curl --form "htmlZip=@files.zip" --form metadata='{"titles":["Semantic Book"],"creators":[{"firstName": "Frank","lastName": "Salliau","roles":["author"]}],"subjects":["news","world"],"language":"en","identifier":{"value":"urn:1235-568-78910"},"tableOfContents":[{"title":"Search","resource":"search.xhtml"},{"title":"Introduction","resource":"introduction.html"},{"title":"Etymology","resource":"etymology.html"},{"title":"History","resource":"history.html"},{"title":"Geography","resource":"geography.html"},{"title":"Administration","resource":"administration.html"},{"title":"Cityscape","resource":"cityscape.html"},{"title":"Economy","resource":"economy.html"},{"title":"Demographics","resource":"demographics.html"},{"title":"Culture and Contemporary Life","resource":"culture_and_contemporary_life.html"},{"title":"Education","resource":"education.html"},{"title":"Environment","resource":"environment.html"},{"title":"Olympic Games","resource":"olympic_games.html"},{"title":"Special Olympics","resource":"special_olympics.html"},{"title":"International Relations","resource":"international_relations.html"},{"title":"Other Locations Named After Athens","resource":"other_locations_named_after_athens.html"},{"title":"See Also","resource":"see_also.html"},{"title":"References","resource":"references.html"},{"title":"External Links","resource":"external_links.html"}]}'  http://http://api-dev.freme-project.eu/current/e-publishing/html > semantic_book.epub
```

[files.zip](https://github.com/freme-project/e-Publishing/files/88737/files.zip)

**Comment by pheyvaer** [comment]
OK, so it fails if one of the submitted files is not valid.

**Comment by jnehring** [comment]
Maybe we can add some validation and return an error message instead of invalid ebook?
